### ISSUE TITLE
Candidates IV - Resume - documentation

### ISSUE THREAD

**Issue by khushichoudhary1020** [shamiitltd/ems#54]
https://www.figma.com/file/ligFMIkbpRedAyhvEFHCAJ/Candidate-and-Job-Board-Editor?type=design&node-id=0-1&mode=design&t=DL02KAiiwL4esp0J-0

**Comment by Mr-barnes** [comment]
[UX report-by-G.pdf](https://github.com/shamiitltd/ems/files/12894141/UX.report-by-G.pdf)
